const BUILD="kairos-command-hub-20260712-27";
const root=document.querySelector("#kairos-hub");
const state={health:null,capabilities:null,latency:null,activeCenter:null,activeJobs:0,job:null,plan:null,approval:null};
const centers=[
 {id:"knowledge",icon:"⌘",title:"Knowledge",description:"Doctrine, research, decisions, and reusable intelligence.",children:[
  ["Knowledge Library","Search and use authoritative MMG knowledge.","Open Library","knowledge-library"],["Research Brief","Turn a question into a sourced working brief.","Start Research","research-brief"],["Decision Record","Preserve an approved decision and its context.","Record Decision","decision-record"]]},
 {id:"content",icon:"✦",title:"Content",description:"Website, publishing, visual assets, and production.",children:[
  ["Website Retool","Plan, approve, execute, and verify a staging website change.","Start Website Retool","website"],["Publishing Studio","Create books, manuscripts, and editorial packages.","Create Publication","publishing-studio"],["Creative Studio","Produce campaign-ready creative asset packages.","Create Asset","creative-studio"]]},
 {id:"business",icon:"◇",title:"Business",description:"Products, revenue, growth, and commercial intelligence.",children:[
  ["Product Launch","Prepare a complete product launch package.","Start Product Launch","product-launch"],["Revenue Intelligence","Analyze supplied commerce performance.","Run Revenue Review","revenue-intelligence"],["Growth Plan","Convert an objective into a measurable growth plan.","Build Growth Plan","growth-plan"]]},
 {id:"customers",icon:"◎",title:"Customers",description:"Visitor activity, customer journeys, and delivery.",children:[
  ["Visitor Activity","Review traffic evidence without simulated counts.","Review Activity","visitor-activity"],["Customer Portal","Projects, approvals, files, messages, and billing.","Open Customer Hub","customer-portal"],["Deliverables","Review and release completed customer work.","View Deliverables","deliverables"]]},
 {id:"operations",icon:"⚙",title:"Operations",description:"Runtime, work queues, releases, and verified system health.",children:[
  ["Runtime Health","Live services, response time, and capability state.","Refresh Health","health"],["Work Queue","Active and completed execution across MMG.","View Queue","work-queue"],["Release Control","Verification, approvals, rollback, and release evidence.","Open Releases","release-control"]]}
];

render(); refreshTelemetry(); setInterval(refreshTelemetry,15000);

function render(){
 const ready=Boolean(state.health&&(state.health.status==="ready"||state.health.status==="ok"));
 root.innerHTML=`<header class="topbar"><div class="brand"><span class="brand-mark" aria-hidden="true"></span><div><strong>Kairos</strong><span>Mindset Media Group Operating System</span></div></div><div class="system-strip"><span>${new Date().toLocaleString([], {month:"short",day:"numeric",hour:"numeric",minute:"2-digit"})}</span><span class="live-state"><i class="state-dot ${state.health?ready?"":"offline":"checking"}"></i>${state.health?ready?"Systems online":"Attention required":"Connecting"}</span></div></header>
 <section class="hero"><div><p class="eyebrow">Executive Command Center</p><h1>One objective.<br>Coordinated execution.</h1><p class="hero-copy">Direct the MMG ecosystem from one place. Kairos turns an objective into a concise approval package, executes through connected capabilities, and returns the finished work with evidence.</p></div><aside class="pulse-panel"><div class="pulse-head"><strong>Operating signal</strong><span class="quiet">${ready?"Live":"Waiting for runtime"}</span></div><div class="wave ${ready?"active":""}" aria-hidden="true">${[35,70,46,88,52,76,38,92,58,80,44,68,32,84,54,74].map((h,i)=>`<i style="--h:${h}%;--d:-${i*.09}s"></i>`).join("")}</div></aside></section>
 <section class="metrics" aria-label="Live operating metrics">${metric("Runtime",ready?"Online":"Checking",state.latency?`${state.latency} ms response`:"Awaiting response",ready?"live":"limited")}${metric("Active work",String(state.activeJobs),state.activeJobs===1?"execution in progress":"no execution running","live")}${metric("Capabilities",capabilityCount(),state.capabilities?"reported by runtime":"syncing registry","live")}${metric("Visitors","—","analytics source not connected","limited")}</section>
 <div class="section-head"><div><p class="eyebrow">Operating Centers</p><h2>Choose where Kairos should work</h2></div><p>Five centers. Clear actions. Finished work.</p></div>
 <section class="parent-grid">${centers.map(center=>parentCard(center,ready)).join("")}</section>
 ${state.activeCenter?workspace(centers.find(c=>c.id===state.activeCenter)):""}`;
 bind();
}
function metric(label,value,detail,status){return `<article class="metric" data-state="${status}"><span>${label}</span><strong>${escapeHTML(value)}</strong><small>${escapeHTML(detail)}</small></article>`}
function capabilityCount(){const c=state.capabilities?.capabilities||state.health?.capabilities;return c&&typeof c==="object"?String(Object.values(c).filter(v=>v==="available"||v===true).length):"—"}
function parentCard(c,ready){const meter=c.id==="operations"?(ready?100:22):c.id==="content"?72:c.id==="knowledge"?58:c.id==="business"?42:34;return `<button class="parent-card" data-center="${c.id}"><div class="card-top"><span class="parent-icon">${c.icon}</span><span class="card-signal"><i></i>${c.id==="operations"&&ready?"LIVE":"READY"}</span></div><h3>${c.title}</h3><p>${c.description}</p><div class="mini-meter"><span style="--meter:${meter}%"></span></div><div class="card-foot"><b>${c.children.length} actions</b><span>Open center →</span></div></button>`}
function workspace(c){return `<section class="workspace" id="workspace"><header class="workspace-head"><div><p class="eyebrow">${c.title} Center</p><h2>What do you want to accomplish?</h2></div><button class="back" data-back>Return to Command Center</button></header><div class="children">${c.children.map(child=>`<article class="child-card"><p class="eyebrow">${c.title}</p><h3>${child[0]}</h3><p>${child[1]}</p><button class="child-action" data-child="${child[3]}">${child[2]}</button></article>`).join("")}</div>${state.job?jobPanel():""}</section>`}
function jobPanel(){const j=state.job;return `<section class="job"><p class="eyebrow">Website Retool</p><h3>${j.mode==="complete"?"Deliverable ready":j.mode==="review"?"Review execution summary":"What should Kairos change?"}</h3>${j.mode==="input"?`<p>Describe the outcome. Kairos will apply the established MMG website vision, inspect the staging source, and return only the proposed execution summary.</p><textarea class="objective" id="objective" maxlength="2000" placeholder="Example: Retool the homepage so visitors immediately understand how MMG's books, AI, business, and creator education work together as one ecosystem.">${escapeHTML(j.objective||"")}</textarea><div class="job-actions"><button class="primary" data-plan>Prepare Execution Summary</button><button class="secondary" data-close-job>Cancel</button></div>`:j.mode==="working"?progressPanel(j.message):j.mode==="review"?reviewPanel():j.mode==="executing"?progressPanel(j.message):completionPanel(j.result,j.error)}</section>`}
function progressPanel(message){return `<div class="stage-row"><span class="stage done">1 · Request</span><span class="stage active">2 · Prepare</span><span class="stage">3 · Approve</span><span class="stage">4 · Deliver</span></div><p class="status-line"><i class="spinner"></i>${escapeHTML(message)}</p>`}
function reviewPanel(){const p=state.plan||{},plan=p.plan||{},changes=(plan.changes||[]).filter(x=>x.changeType!=="no-change");return `<div class="stage-row"><span class="stage done">1 · Request</span><span class="stage done">2 · Prepare</span><span class="stage active">3 · Approve</span><span class="stage">4 · Deliver</span></div><div class="summary-card"><h4>${escapeHTML(p.summary||"Execution package prepared")}</h4><p>${escapeHTML(plan.strategy||"Kairos prepared a bounded staging change.")}</p><ul>${changes.slice(0,4).map(x=>`<li><strong>${escapeHTML(x.filename||"Website")}</strong> — ${escapeHTML(x.purpose||x.expectedOutcome||"Approved change")}</li>`).join("")}</ul><p class="quiet">Target: ${escapeHTML(plan.targetTheme?.name||"Kairos Staging")} · Live website remains unchanged until separately released.</p></div><div class="job-actions"><button class="primary" data-execute>Approve & Execute</button><button class="secondary" data-revise>Revise Request</button><button class="secondary" data-close-job>Cancel</button></div>`}
function completionPanel(result,error){if(error)return `<p class="error">${escapeHTML(error)}</p><div class="job-actions"><button class="primary" data-plan>Retry</button><button class="secondary" data-close-job>Close</button></div>`;if(result?.deliverable)return `<div class="stage-row"><span class="stage done">1 · Request</span><span class="stage done">2 · Execute</span><span class="stage done">3 · Verify</span><span class="stage done">4 · Deliver</span></div><div class="deliverable"><strong>${escapeHTML(result.summary||"Deliverable completed.")}</strong><pre style="white-space:pre-wrap;font:inherit;color:#dce7ef">${escapeHTML(result.deliverable)}</pre><small>${escapeHTML(result.completedAt||"")}</small></div><div class="job-actions"><button class="secondary" data-close-job>Close</button></div>`;const files=result?.execution?.filesWritten||[];return `<div class="stage-row"><span class="stage done">1 · Request</span><span class="stage done">2 · Prepare</span><span class="stage done">3 · Approve</span><span class="stage done">4 · Deliver</span></div><div class="deliverable"><strong>${escapeHTML(result?.summary||"Website retool completed and verified.")}</strong><p>${files.length} verified staging file${files.length===1?"":"s"} updated. The published website was not changed.</p></div><div class="job-actions"><button class="primary" data-new-job>Start Another Retool</button><button class="secondary" data-close-job>Close</button></div>`}
function bind(){document.querySelectorAll("[data-center]").forEach(b=>b.onclick=()=>{state.activeCenter=b.dataset.center;state.job=null;render();setTimeout(()=>document.querySelector("#workspace")?.scrollIntoView({behavior:"smooth"}),20)});document.querySelector("[data-back]")?.addEventListener("click",()=>{state.activeCenter=null;state.job=null;render()});document.querySelectorAll("[data-child]").forEach(b=>b.onclick=()=>openChild(b.dataset.child));document.querySelector("[data-close-job]")?.addEventListener("click",()=>{state.job=null;render()});document.querySelector("[data-plan]")?.addEventListener("click",preparePlan);document.querySelector("[data-execute]")?.addEventListener("click",executePlan);document.querySelector("[data-revise]")?.addEventListener("click",()=>{state.job={mode:"input",objective:state.job.objective};state.plan=null;render()});document.querySelector("[data-new-job]")?.addEventListener("click",()=>{state.job={mode:"input",objective:""};state.plan=null;render()})}
function openChild(type){if(type==="health"){refreshTelemetry(true);return}state.job={mode:"input",objective:"",action:type};render();setTimeout(()=>document.querySelector(".job")?.scrollIntoView({behavior:"smooth"}),20)}
async function refreshTelemetry(scroll=false){const start=performance.now();try{const [h,c]=await Promise.all([fetchJSON("/api/health"),fetchJSON("/api/capabilities")]);state.health=h.body;state.capabilities=c.body;state.latency=Math.max(1,Math.round(performance.now()-start));}catch{state.health={status:"unavailable"};state.latency=null}render();if(scroll)setTimeout(()=>document.querySelector(".metrics")?.scrollIntoView({behavior:"smooth"}),20)}
async function preparePlan(){const objective=document.querySelector("#objective")?.value.trim()||state.job?.objective||"",action=state.job?.action||"website";if(objective.length<3){state.job={mode:"complete",action,objective,error:"Describe the outcome before Kairos begins."};render();return}state.job={mode:"working",action,objective,message:"Kairos is producing the requested deliverable…"};state.activeJobs=1;render();try{if(action==="website"){const submitted=await submitJob("/api/shopify/staging/plan/jobs",{objective});const body=await pollJob(submitted,"planning");state.plan=body;state.job={mode:"review",action,objective}}else{const {response,body}=await fetchJSON("/api/hub/run",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,objective})});if(!response.ok)throw new Error(body?.error?.message||"Kairos could not complete this action.");state.job={mode:"complete",action,objective,result:body}}}catch(error){state.job={mode:"complete",action,objective,error:error.message||"Kairos could not complete this action."}}finally{state.activeJobs=0;render()}}
async function executePlan(){const plan=state.plan;if(!plan)return;const approval={status:"approved",approvedAt:new Date().toISOString(),build:BUILD,planID:plan.planID,actionID:plan.actionID,targetThemeID:plan?.plan?.targetTheme?.gid||"",sourceHashes:plan?.plan?.sourceHashes||{},objective:plan.objective||state.job.objective};state.approval=approval;state.job={mode:"executing",objective:state.job.objective,message:"Executing the approved staging change and verifying the finished result…"};state.activeJobs=1;render();try{const submitted=await submitJob("/api/shopify/staging/execute/jobs",{plan,approval});const body=await pollJob(submitted,"execution");state.job={mode:"complete",objective:state.job.objective,result:body};}catch(error){state.job={mode:"complete",objective:state.job.objective,error:error.message||"The approved website job did not complete."}}finally{state.activeJobs=0;render()}}
async function submitJob(url,payload){const {response,body}=await fetchJSON(url,{method:"POST",headers:{"Content-Type":"application/json","X-MMG-Client-Build":BUILD},credentials:"include",body:JSON.stringify(payload)});if(!response.ok||!body?.jobID)throw new Error(body?.error?.message||body?.summary||`Kairos returned ${response.status}.`);return body}
async function pollJob(submitted,type){const deadline=Date.now()+10*60*1000;while(Date.now()<deadline){await new Promise(resolve=>setTimeout(resolve,2200));const {response,body}=await fetchJSON(submitted.pollURL||`/api/shopify/staging/${type}/jobs/${submitted.jobID}`,{credentials:"include"});if(body?.status==="completed"&&body?.result)return body.result;if(["needs-attention","failed","cancelled"].includes(body?.status)||(!response.ok&&response.status!==202))throw new Error(body?.error?.message||body?.summary||`${type} did not complete.`);state.job.message=body?.summary||(type==="planning"?"Kairos is preparing the execution summary…":"Kairos is generating, writing, and verifying the approved change…");render()}throw new Error("Kairos is still working, but this browser session reached its monitoring limit.")}
async function fetchJSON(url,init={}){const response=await fetch(url,{cache:"no-store",...init});const text=await response.text();let body={};try{body=text?JSON.parse(text):{}}catch{body={summary:text}}return{response,body}}
function escapeHTML(value){return String(value??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[c])}
