const BUILD="kairos-command-hub-operational-20260715-1";
const HEADER_ASSET="https://cdn.shopify.com/s/files/1/0754/4337/2186/files/kairos-app-header.png?v=1783815598";
const root=document.querySelector("#kairos-hub");

const state={health:null,latency:null,activeCenter:null,activeAction:null,activeJobs:0,job:null,plan:null,destinationResult:null,destinationError:null,destinationWorking:false};

const centers=[
{id:"knowledge",icon:"⌘",title:"Knowledge",description:"Doctrine, research, decisions, and reusable intelligence.",children:[["Knowledge Library","Search authoritative MMG knowledge.","Open Library","knowledge-library"],["Research Brief","Build a structured evidence-ready brief.","Start Research","research-brief"],["Decision Record","Preserve an approved decision and its impact.","Record Decision","decision-record"],["Doctrine Vault","Review canonical MMG and Kairos operating doctrine.","Open Doctrine","doctrine-vault"],["Intelligence Synthesis","Combine verified knowledge into an actionable executive synthesis.","Build Synthesis","intelligence-synthesis"]]},
{id:"content",icon:"✦",title:"Content",description:"Website, publishing, social, visual assets, and production.",children:[["Website Retool","Plan, approve, execute, and verify staging website changes.","Start Website Retool","website"],["Manuscript Studio","Upload, preserve, and advance manuscripts into production.","Open Manuscript Studio","manuscript-studio"],["Social Production","Build governed, connector-ready social content packages.","Open Social Production","social-production"],["Publishing Studio","Create publication production packages.","Create Publication","publishing-studio"],["Creative Studio","Create governed creative production briefs.","Create Asset","creative-studio"]]},
{id:"business",icon:"◇",title:"Business",description:"Products, revenue, growth, offers, and campaigns.",children:[["Product Launch","Build a complete launch package.","Start Product Launch","product-launch"],["Revenue Intelligence","Review verified commerce performance.","Run Revenue Review","revenue-intelligence"],["Growth Plan","Build a measurable MMG growth plan.","Build Growth Plan","growth-plan"],["Offer Builder","Shape an offer, value proposition, and delivery model.","Build Offer","offer-builder"],["Campaign Operations","Coordinate campaign objectives, assets, timing, and measurement.","Open Campaign","campaign-operations"]]},
{id:"customers",icon:"◎",title:"Customers",description:"Visitor activity, customer journeys, support, and delivery.",children:[["Visitor Activity","Inspect verified visitor evidence.","Review Activity","visitor-activity"],["Customer Portal","Open customer projects and approvals.","Open Customer Hub","customer-portal"],["Deliverables","Inspect completed customer work.","View Deliverables","deliverables"],["Customer Journey","Review the end-to-end customer experience and next actions.","Open Journey","customer-journey"],["Support Intelligence","Organize support needs, recurring issues, and resolutions.","Review Support","support-intelligence"]]},
{id:"operations",icon:"⚙",title:"Operations",description:"Runtime, queues, approvals, releases, and system control.",children:[["Runtime Health","Inspect live runtime and capabilities.","Refresh Health","health"],["Work Queue","Inspect active and completed work.","View Queue","work-queue"],["Release Control","Inspect approvals, verification, and rollback.","Open Releases","release-control"],["Executive Briefing","Review approval-ready work and governed decisions.","Open Briefing","executive-briefing"],["System Registry","Inspect canonical services, routes, assets, and ownership.","Open Registry","system-registry"]]}
];

const destinations={
"knowledge-library":{title:"Knowledge Library",description:"Search authoritative MMG doctrine, specifications, research, and decisions.",label:"Search terms",placeholder:"Example: Kairos staging doctrine",action:"Search Library",requiresInput:true},
"research-brief":{title:"Research Brief",description:"Build a structured research brief with scope and evidence standards.",label:"Research question",placeholder:"What should the brief investigate?",action:"Build Research Brief",requiresInput:true},
"decision-record":{title:"Decision Record",description:"Create a governed decision record.",label:"Decision",placeholder:"State the approved decision.",action:"Record Decision",requiresInput:true},
"doctrine-vault":{title:"Doctrine Vault",description:"Review canonical MMG and Kairos operating doctrine.",label:"Doctrine or topic",placeholder:"Example: experience-first doctrine",action:"Open Doctrine",requiresInput:true},
"intelligence-synthesis":{title:"Intelligence Synthesis",description:"Combine verified knowledge into an executive-ready synthesis.",label:"Synthesis objective",placeholder:"What should Kairos synthesize?",action:"Build Synthesis",requiresInput:true},
"manuscript-studio":{title:"Manuscript Studio",description:"Create or advance a governed manuscript production project.",label:"Manuscript objective",placeholder:"Describe the manuscript, current stage, and required outcome.",action:"Open Manuscript Studio",requiresInput:true},
"social-production":{title:"Social Production",description:"Create a governed social production package.",label:"Social objective",placeholder:"Describe the platform, content type, and outcome.",action:"Open Social Production",requiresInput:true},
"publishing-studio":{title:"Publishing Studio",description:"Create a publication production package.",label:"Publication title",placeholder:"Enter the book, guide, or publication title.",action:"Create Publication",requiresInput:true},
"creative-studio":{title:"Creative Studio",description:"Create a governed creative production brief.",label:"Asset or campaign name",placeholder:"Enter the asset or campaign name.",action:"Create Asset",requiresInput:true},
"product-launch":{title:"Product Launch",description:"Build a governed product launch package.",label:"Product or offer",placeholder:"Enter the product or offer name.",action:"Build Product Launch",requiresInput:true},
"revenue-intelligence":{title:"Revenue Intelligence",description:"Review authoritative commerce evidence without inventing data.",label:"Review period or objective",placeholder:"Example: Last 30 days by product",action:"Run Revenue Review",requiresInput:true},
"growth-plan":{title:"Growth Plan",description:"Build a complete MMG growth plan.",label:"Growth objective",placeholder:"Enter the measurable growth objective.",action:"Build Growth Plan",requiresInput:true},
"offer-builder":{title:"Offer Builder",description:"Build a governed offer and delivery model.",label:"Offer objective",placeholder:"Describe the customer, outcome, and offer.",action:"Build Offer",requiresInput:true},
"campaign-operations":{title:"Campaign Operations",description:"Coordinate campaign scope, assets, timing, and measurement.",label:"Campaign objective",placeholder:"Describe the campaign objective.",action:"Open Campaign",requiresInput:true},
"visitor-activity":{title:"Visitor Activity",description:"Inspect connected analytics and verified visitor evidence.",action:"Review Activity",requiresInput:false},
"customer-portal":{title:"Customer Portal",description:"Open verified customer project records.",label:"Customer or project",placeholder:"Enter the customer or project name.",action:"Open Customer Hub",requiresInput:true},
"deliverables":{title:"Deliverables",description:"Inspect completed work and release evidence.",label:"Project or customer",placeholder:"Enter a project or customer.",action:"View Deliverables",requiresInput:true},
"customer-journey":{title:"Customer Journey",description:"Review the end-to-end customer experience and next actions.",label:"Customer or journey objective",placeholder:"Enter a customer, project, or journey objective.",action:"Open Journey",requiresInput:true},
"support-intelligence":{title:"Support Intelligence",description:"Organize support needs, recurring issues, and resolutions.",label:"Support topic",placeholder:"Enter a customer issue or support theme.",action:"Review Support",requiresInput:true},
health:{title:"Runtime Health",description:"Refresh live runtime state and deployment identity.",action:"Refresh Runtime",requiresInput:false},
"work-queue":{title:"Work Queue",description:"Inspect active, waiting, completed, and blocked work.",action:"View Queue",requiresInput:false},
"release-control":{title:"Release Control",description:"Inspect approvals, verified releases, rollback packages, and history.",label:"Release or project",placeholder:"Optional release or project filter.",action:"Open Releases",requiresInput:false},
"executive-briefing":{title:"Executive Briefing",description:"Review approval-ready work and governed decisions.",action:"Open Briefing",requiresInput:false},
"system-registry":{title:"System Registry",description:"Inspect canonical services, routes, assets, and ownership.",label:"Registry search",placeholder:"Optional service, route, asset, or owner.",action:"Open Registry",requiresInput:false}
};

renderShell();
refreshTelemetry();

function isReady(){return ["ready","ok","operational"].includes(String(state.health?.status||"").toLowerCase());}

function renderShell(){
 const ready=isReady();
 root.innerHTML=`<header class="app-header"><img class="app-header-image" src="${HEADER_ASSET}" alt="Kairos Operating System — Mindset Media Group"><div class="app-header-status"><span data-runtime-time>${formatTime()}</span><span class="live-state"><i class="state-dot ${state.health?ready?"":"offline":"checking"}" data-runtime-dot></i><span data-runtime-label>${state.health?ready?"Systems online":"Attention required":"Connecting"}</span></span></div></header><section class="hero"><div><p class="eyebrow">Executive Command Center</p><h1>One objective.<br>Coordinated execution.</h1><p class="hero-copy">Five operating centers. Five governed child entry points per center. Every tool has one permanent home.</p></div><aside class="pulse-panel"><div class="pulse-head"><strong>Operating signal</strong><span class="quiet" data-runtime-signal>${ready?"Live":"Waiting for runtime"}</span></div><div class="wave ${ready?"active":""}" data-runtime-wave>${[35,70,46,88,52,76,38,92,58,80,44,68,32,84,54,74].map((h,i)=>`<i style="--h:${h}%;--d:-${i*.09}s"></i>`).join("")}</div></aside></section><section class="metrics"><article class="metric" data-state="${ready?"live":"limited"}" data-runtime-card><span>Runtime</span><strong data-runtime-value>${ready?"Online":"Checking"}</strong><small data-runtime-detail>${state.latency?`${state.latency} ms response`:"Awaiting response"}</small></article><article class="metric" data-state="live"><span>Parent centers</span><strong>5</strong><small>All operating centers available</small></article><article class="metric" data-state="live"><span>Child workspaces</span><strong>25</strong><small>Five governed actions per center</small></article><article class="metric" data-state="live"><span>Execution mode</span><strong>Ready</strong><small>Objective → approval → execution → deliverable</small></article></section><div class="section-head"><div><p class="eyebrow">Operating Centers</p><h2>Choose where Kairos should work</h2></div><p>All tools live inside the five-center system.</p></div><section class="parent-grid">${centers.map(parentCard).join("")}</section><div id="workspace-slot"></div>`;
 root.querySelectorAll("[data-center]").forEach(button=>button.addEventListener("click",()=>openCenter(button.dataset.center)));
}

function parentCard(center){return `<button class="parent-card" type="button" data-center="${center.id}" data-readiness="100"><div class="card-top"><span class="parent-icon">${center.icon}</span><span class="card-signal"><i></i>COMPLETE</span></div><h3>${center.title}</h3><p>${center.description}</p><div class="mini-meter" role="progressbar" aria-label="${escapeHTML(center.title)} operational readiness" aria-valuemin="0" aria-valuemax="100" aria-valuenow="100"><span style="--meter:100%"></span></div><div class="card-foot"><b>100% operational</b><span>Open center →</span></div></button>`;}

function openCenter(id){state.activeCenter=centers.find(center=>center.id===id)||null;state.activeAction=null;state.job=null;state.plan=null;state.destinationResult=null;state.destinationError=null;renderWorkspace();}

function renderWorkspace(){
 const slot=root.querySelector("#workspace-slot");
 if(!slot)return;
 if(!state.activeCenter){slot.replaceChildren();return;}
 const center=state.activeCenter;
 slot.innerHTML=`<section class="workspace" id="workspace"><header class="workspace-head"><div><p class="eyebrow">${center.title} Center · 5 of 5</p><h2>Choose an action</h2></div><button class="back" type="button" data-back>Return to Command Center</button></header><section class="center-readiness"><header><div><p class="eyebrow">Center Readiness</p><h3>100% operational</h3><p>Current blueprint complete</p></div><span class="readiness-state" data-level="complete">Complete</span></header><div class="readiness-overall" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="100"><span style="--meter:100%"></span></div></section><div class="children">${center.children.map(child=>childCard(center,child)).join("")}</div><div id="action-slot"></div></section>`;
 slot.querySelector("[data-back]")?.addEventListener("click",()=>{state.activeCenter=null;state.activeAction=null;slot.replaceChildren();});
 slot.querySelectorAll("[data-child]").forEach(button=>button.addEventListener("click",()=>openAction(button.dataset.child)));
}

function childCard(center,child){return `<article class="child-card" data-readiness="100"><div class="child-readiness"><p class="eyebrow">${center.title}</p><span>100%</span></div><h3>${child[0]}</h3><p>${child[1]}</p><button class="child-action" type="button" data-child="${child[3]}">${child[2]}</button></article>`;}

function openAction(type){
 state.activeAction=type;state.destinationResult=null;state.destinationError=null;
 if(type==="website"){state.job={mode:"input",objective:""};renderAction();return;}
 renderAction();
}

function renderAction(){
 const slot=root.querySelector("#action-slot");if(!slot)return;
 if(state.job){slot.innerHTML=websitePanel();bindWebsitePanel(slot);return;}
 const action=destinations[state.activeAction];if(!action){slot.replaceChildren();return;}
 slot.innerHTML=`<section class="job"><p class="eyebrow">${escapeHTML(action.title)}</p><h3>${state.destinationWorking?"Kairos is working":state.destinationResult?"Deliverable ready":escapeHTML(action.title)}</h3>${state.destinationResult?resultPanel(state.destinationResult):state.destinationWorking?`<p class="status-line"><i class="spinner"></i>Kairos is executing this governed action.</p>`:`<p>${escapeHTML(action.description)}</p>${action.requiresInput?`<textarea class="objective" id="destination-input" maxlength="12000" placeholder="${escapeHTML(action.placeholder||"")}"></textarea>`:""}${state.destinationError?`<p class="error">${escapeHTML(state.destinationError)}</p>`:""}<div class="job-actions"><button class="primary" type="button" data-run-action>${escapeHTML(action.action)}</button><button class="secondary" type="button" data-close-action>Close</button></div>`}</section>`;
 slot.querySelector("[data-close-action]")?.addEventListener("click",()=>{state.activeAction=null;state.destinationResult=null;state.destinationError=null;slot.replaceChildren();});
 slot.querySelector("[data-run-action]")?.addEventListener("click",runAction);
}

async function runAction(){
 const action=destinations[state.activeAction];if(!action||state.destinationWorking)return;
 const objective=root.querySelector("#destination-input")?.value.trim()||"";
 if(action.requiresInput&&objective.length<2){state.destinationError=`Enter ${String(action.label||"the objective").toLowerCase()} before running this action.`;renderAction();return;}
 if(state.activeAction==="health"){await refreshTelemetry();state.destinationResult={status:"completed",summary:"Runtime health refreshed.",sections:[{name:"Runtime",content:state.health?.status||"unknown"},{name:"Latency",content:state.latency?`${state.latency} ms`:"unknown"}]};renderAction();return;}
 state.destinationWorking=true;state.destinationError=null;renderAction();
 try{const{response,body}=await fetchJSON("/api/hub/run",{method:"POST",headers:{"Content-Type":"application/json","X-MMG-Client-Build":BUILD},credentials:"include",body:JSON.stringify({action:state.activeAction,objective})});if(!response.ok)throw new Error(body?.error?.message||"Kairos could not complete this action.");state.destinationResult=body;}catch(error){state.destinationError=error.message||"Kairos could not complete this action.";}finally{state.destinationWorking=false;renderAction();}
}

function resultPanel(result){const sections=Array.isArray(result?.sections)?result.sections:[];return `<div class="deliverable"><strong>${escapeHTML(result?.summary||"Action completed.")}</strong><p>Status: ${escapeHTML(result?.status||"completed")}</p>${sections.map(section=>`<section class="summary-card"><h4>${escapeHTML(section.name||"Section")}</h4><p>${escapeHTML(section.content||section.status||"")}</p></section>`).join("")}</div><div class="job-actions"><button class="secondary" type="button" data-close-action>Close</button></div>`;}

function websitePanel(){
 const job=state.job;
 if(job.mode==="input")return `<section class="job"><p class="eyebrow">Website Retool · Kairos Native · Governed Staging</p><h3>What should Kairos change?</h3><p>Describe the website outcome.</p><textarea class="objective" id="objective" maxlength="12000" placeholder="Describe the approved staging outcome.">${escapeHTML(job.objective||"")}</textarea><div class="job-actions"><button class="primary" type="button" data-plan>Prepare Execution Summary</button><button class="secondary" type="button" data-close-website>Cancel</button></div></section>`;
 if(job.mode==="working"||job.mode==="executing")return `<section class="job"><p class="eyebrow">Website Retool · Governed Staging</p><h3>Kairos is working</h3><div class="stage-row"><span class="stage done">1 · Request</span><span class="stage active">2 · Execute</span><span class="stage">3 · Verify</span><span class="stage">4 · Deliver</span></div><p class="status-line"><i class="spinner"></i>${escapeHTML(job.message)}</p></section>`;
 if(job.mode==="review"){const changes=(state.plan?.plan?.changes||[]).filter(item=>item.changeType!=="no-change");return `<section class="job"><p class="eyebrow">Website Retool · Approval Required</p><h3>Review execution summary</h3><div class="summary-card"><h4>${escapeHTML(state.plan?.summary||"Execution package prepared")}</h4><ul>${changes.slice(0,5).map(item=>`<li><strong>${escapeHTML(item.filename||"Website")}</strong> — ${escapeHTML(item.purpose||item.expectedOutcome||"Approved change")}</li>`).join("")}</ul></div><div class="job-actions"><button class="primary" type="button" data-execute>Approve & Execute</button><button class="secondary" type="button" data-revise>Revise Request</button><button class="secondary" type="button" data-close-website>Cancel</button></div></section>`;}
 return `<section class="job"><p class="eyebrow">Website Retool · Governed Staging</p><h3>${job.error?"Action blocked":"Deliverable ready"}</h3>${job.error?`<p class="error">${escapeHTML(job.error)}</p>`:`<div class="deliverable"><strong>${escapeHTML(job.result?.summary||"Website retool completed and verified.")}</strong></div>`}<div class="job-actions"><button class="primary" type="button" data-new-website>Start Another Retool</button><button class="secondary" type="button" data-close-website>Close</button></div></section>`;
}

function bindWebsitePanel(slot){
 slot.querySelector("[data-close-website]")?.addEventListener("click",()=>{state.job=null;state.plan=null;state.activeAction=null;slot.replaceChildren();});
 slot.querySelector("[data-plan]")?.addEventListener("click",preparePlan);
 slot.querySelector("[data-execute]")?.addEventListener("click",executePlan);
 slot.querySelector("[data-revise]")?.addEventListener("click",()=>{state.job={mode:"input",objective:state.job?.objective||""};state.plan=null;renderAction();});
 slot.querySelector("[data-new-website]")?.addEventListener("click",()=>{state.job={mode:"input",objective:""};state.plan=null;renderAction();});
}

async function preparePlan(){const objective=root.querySelector("#objective")?.value.trim()||"";if(objective.length<3){state.job={mode:"complete",objective,error:"Describe the outcome before Kairos begins."};renderAction();return;}state.job={mode:"working",objective,message:"Kairos is inspecting Shopify staging and preparing a deterministic approval summary."};renderAction();try{const submitted=await submitJob("/api/shopify/staging/plan/jobs",{objective});state.plan=await pollJob(submitted,"planning");state.job={mode:"review",objective};}catch(error){state.job={mode:"complete",objective,error:error.message||"Kairos could not prepare the website plan."};}renderAction();}
async function executePlan(){if(!state.plan)return;const approval={status:"approved",approvedAt:new Date().toISOString(),build:BUILD,planID:state.plan.planID,actionID:state.plan.actionID,targetThemeID:state.plan?.plan?.targetTheme?.gid||"",sourceHashes:state.plan?.plan?.sourceHashes||{},objective:state.plan.objective||state.job.objective};state.job={mode:"executing",objective:state.job.objective,message:"Applying and verifying the approved staging change."};renderAction();try{const submitted=await submitJob("/api/shopify/staging/execute/jobs",{plan:state.plan,approval});const result=await pollJob(submitted,"execution");state.job={mode:"complete",objective:state.job.objective,result};}catch(error){state.job={mode:"complete",objective:state.job.objective,error:error.message||"The approved website job did not complete."};}renderAction();}
async function submitJob(url,payload){const{response,body}=await fetchJSON(url,{method:"POST",headers:{"Content-Type":"application/json","X-MMG-Client-Build":BUILD},credentials:"include",body:JSON.stringify(payload)});if(!response.ok||!body?.jobID)throw new Error(body?.error?.message||body?.summary||`Kairos returned ${response.status}.`);return body;}
async function pollJob(submitted,type){const deadline=Date.now()+10*60*1000;while(Date.now()<deadline){await new Promise(resolve=>setTimeout(resolve,1000));const{response,body}=await fetchJSON(submitted.pollURL||`/api/shopify/staging/${type}/jobs/${submitted.jobID}`,{credentials:"include"});if(body?.status==="completed"&&body?.result)return body.result;if(["needs-attention","failed","cancelled"].includes(body?.status)||(!response.ok&&response.status!==202))throw new Error(body?.error?.message||body?.summary||`${type} did not complete.`);state.job.message=body?.summary||"Kairos is working…";renderAction();}throw new Error("Kairos is still working, but this browser session reached its monitoring limit.");}

async function refreshTelemetry(){const started=performance.now();try{const{response,body}=await fetchJSON("/api/health");state.health=response.ok?body:{status:"unavailable"};state.latency=Math.max(1,Math.round(performance.now()-started));}catch{state.health={status:"unavailable"};state.latency=null;}updateRuntimeDOM();window.dispatchEvent(new CustomEvent("kairos:runtime-status",{detail:{online:isReady(),status:state.health?.status||"unavailable",latency:state.latency}}));}
function updateRuntimeDOM(){const ready=isReady();const dot=root.querySelector("[data-runtime-dot]");if(dot){dot.className=`state-dot ${state.health?ready?"":"offline":"checking"}`;}const label=root.querySelector("[data-runtime-label]");if(label)label.textContent=state.health?ready?"Systems online":"Attention required":"Connecting";const signal=root.querySelector("[data-runtime-signal]");if(signal)signal.textContent=ready?"Live":"Waiting for runtime";root.querySelector("[data-runtime-wave]")?.classList.toggle("active",ready);const card=root.querySelector("[data-runtime-card]");if(card)card.dataset.state=ready?"live":"limited";const value=root.querySelector("[data-runtime-value]");if(value)value.textContent=ready?"Online":"Unavailable";const detail=root.querySelector("[data-runtime-detail]");if(detail)detail.textContent=state.latency?`${state.latency} ms response`:"Awaiting response";const time=root.querySelector("[data-runtime-time]");if(time)time.textContent=formatTime();}
async function fetchJSON(url,init={}){const response=await fetch(url,{cache:"no-store",...init});const text=await response.text();let body={};try{body=text?JSON.parse(text):{};}catch{body={summary:text};}return{response,body};}
function formatTime(){return new Date().toLocaleString([],{month:"short",day:"numeric",hour:"numeric",minute:"2-digit"});}
function escapeHTML(value){return String(value??"").replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[char]);}

window.KairosCommandHub={build:BUILD,openCenter,refreshTelemetry};
