const BUILD="kairos-creation-engine-20260712-1";
const state={open:false,working:false,error:"",result:null,type:"social_content",objective:""};

function mount(){const button=document.createElement("button");button.className="creation-engine-launch";button.textContent="Open Creation Engine";button.onclick=()=>{state.open=true;render()};document.body.appendChild(button);render()}

function render(){document.querySelector("#creation-engine-overlay")?.remove();if(!state.open)return;const overlay=document.createElement("div");overlay.id="creation-engine-overlay";overlay.className="creation-engine-overlay";overlay.innerHTML=`<section class="creation-engine-panel"><header><div><p class="eyebrow">Kairos Production</p><h2>Creation Engine</h2><p>Create TikTok and Facebook content, product-page assets, or a governed book package.</p></div><button data-close aria-label="Close">×</button></header>${state.result?resultView():inputView()}</section>`;document.body.appendChild(overlay);overlay.querySelector("[data-close]").onclick=()=>{state.open=false;render()};overlay.querySelector("[data-run]")?.addEventListener("click",run);overlay.querySelector("[data-new]")?.addEventListener("click",()=>{state.result=null;state.error="";render()});overlay.querySelector("[data-download]")?.addEventListener("click",download)}

function inputView(){return `<label>What should Kairos create?<select id="ce-type"><option value="social_content" ${state.type==="social_content"?"selected":""}>TikTok + Facebook content package</option><option value="product_asset_copy" ${state.type==="product_asset_copy"?"selected":""}>Product page + website asset package</option><option value="book_package" ${state.type==="book_package"?"selected":""}>Book development package</option></select></label><label>Objective<textarea id="ce-objective" maxlength="12000" placeholder="Example: Create a seven-day TikTok and Facebook campaign for AI for Beginners.">${esc(state.objective)}</textarea></label><p class="creation-engine-note">This engine creates text, scripts, copy, plans, and production briefs. Image, video, and audio generation are not enabled in the current launch build.</p>${state.error?`<p class="creation-engine-error">${esc(state.error)}</p>`:""}<button class="primary" data-run ${state.working?"disabled":""}>${state.working?"Kairos is creating…":"Create Package"}</button>`}

function resultView(){const result=state.result?.result||{};return `<div class="creation-engine-result"><div class="creation-engine-status"><span>Review required</span><strong>${esc(state.result?.type||"package")}</strong></div><pre>${esc(JSON.stringify(result,null,2))}</pre><p class="creation-engine-note">No external publication or website change occurred. Approve the package before routing product copy into the governed Shopify retool workflow.</p><div class="creation-engine-actions"><button class="primary" data-download>Download JSON Package</button><button class="secondary" data-new>Create Another</button></div></div>`}

async function run(){state.type=document.querySelector("#ce-type")?.value||"social_content";state.objective=document.querySelector("#ce-objective")?.value.trim()||"";if(state.objective.length<3){state.error="Describe what Kairos should create.";render();return}state.working=true;state.error="";render();try{const response=await fetch("/api/content/generate",{method:"POST",headers:{"Content-Type":"application/json","X-MMG-Client-Build":BUILD},credentials:"include",body:JSON.stringify({type:state.type,objective:state.objective})});const body=await response.json();if(!response.ok)throw new Error(body?.error?.message||"Kairos could not create the package.");state.result=body}catch(error){state.error=error.message||"Kairos could not create the package."}finally{state.working=false;render()}}

function download(){const text=JSON.stringify(state.result,null,2);const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([text],{type:"application/json"}));a.download=`kairos-${state.type}-${Date.now()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function esc(v){return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[c])}
mount();
