const BUILD="kairos-abos-v2-20260723-1";
const root=document.createElement("main");root.id="kairos-executive-os";root.className="abos-shell";document.body.prepend(root);document.body.classList.add("abos-active");
const state={view:"today",health:null,workflows:[],briefing:null,loading:false,error:"",objective:""};
const nav=["today","approvals","create","assets","growth","settings"];
start();
function start(){bindGlobalEvents();refresh();setInterval(refresh,60000);}
async function refresh(){state.loading=true;state.error="";render();const results=await Promise.allSettled([json("/api/health"),json("/api/workflows"),json("/api/executive-briefing/latest")]);if(results[0].status==="fulfilled")state.health=results[0].value.body;if(results[1].status==="fulfilled")state.workflows=results[1].value.body?.workflows||[];if(results[2].status==="fulfilled"&&results[2].value.response.ok)state.briefing=results[2].value.body?.briefing||null;state.loading=false;render();}
function render(){const ready=["ready","ok"].includes(state.health?.status);root.innerHTML=`<header class="abos-topbar"><div class="abos-brand"><div class="abos-mark">K</div><div><strong>Kairos</strong><span>Executive Operating System</span></div></div><div class="abos-status" data-ready="${ready}"><i></i>${ready?"Operating normally":"Checking runtime"}</div></header><div class="abos-layout"><section class="abos-main">${view()}</section><aside class="abos-sidebar"><nav class="abos-nav" aria-label="Primary">${nav.map(item=>`<button data-view="${item}" aria-current="${state.view===item?"page":"false"}">${label(item)}</button>`).join("")}</nav></aside></div>`;bind();}
function view(){if(state.error)return`<p class="abos-error">${esc(state.error)}</p>`;if(state.view==="today")return today();if(state.view==="approvals")return approvals();if(state.view==="create")return create();if(state.view==="assets")return assets();if(state.view==="growth")return growth();return settings();}
function today(){const pending=items().filter(x=>x.state==="pending");const active=state.workflows.filter(x=>x.state==="active");const completed=state.workflows.filter(x=>x.state==="completed");const blocked=state.workflows.filter(x=>x.state==="blocked");return`<section class="abos-hero"><p class="abos-kicker">${windowTitle()}</p><h1>${pending.length?`${pending.length} decisions need you.`:"Kairos is working."}</h1><p>${pending.length?"Review the prepared decisions, approve the low-risk operating plan, and let Kairos continue execution.":"No protected decision is waiting. Kairos will keep producing, measuring, and preparing the next approval window."}</p><div class="abos-actions"><button class="abos-primary" data-open-brief>${pending.length?"Review approvals":"Refresh operating brief"}</button><button class="abos-secondary" data-open-legacy>Advanced operations</button></div></section><section class="abos-grid">${metric("Approvals",pending.length)}${metric("Active work",active.length)}${metric("Completed",completed.length)}${metric("Blocked",blocked.length)}</section><section class="abos-section"><div class="abos-section-head"><h2>Current work</h2><span class="abos-muted">Live governed queue</span></div>${workflowCards(active.length?active:state.workflows.slice(0,5))}</section>`;}
function approvals(){const list=items();return`<section class="abos-hero"><p class="abos-kicker">Unified approval queue</p><h1>${list.filter(x=>x.state==="pending").length||"No"} protected decisions.</h1><p>Review exact outputs, approve safe execution, request a correction, or deny the action. Pricing, publication, spending, customer communication, and destructive changes remain protected.</p>${list.some(x=>x.state==="pending")?`<div class="abos-actions"><button class="abos-primary" data-approve-plan>Approve low-risk plan</button></div>`:""}</section><section class="abos-card-list">${list.length?list.map(approvalCard).join(""):`<div class="abos-empty">Nothing currently needs approval.</div>`}</section>`;}
function create(){return`<section class="abos-hero"><p class="abos-kicker">Objective to execution</p><h1>What should Kairos accomplish?</h1><p>State the outcome once. Kairos will plan, manufacture, validate, package, and route protected actions into the approval queue.</p><textarea class="abos-objective" data-objective placeholder="Example: Build and launch the AI Image Mastery digital product, then create a 14-day social campaign.">${esc(state.objective)}</textarea><div class="abos-actions"><button class="abos-primary" data-run-objective>Start governed work</button><button class="abos-secondary" data-manuscript>Open manuscript production</button><button class="abos-secondary" data-social>Open social production</button></div></section>`;}
function assets(){const completed=state.workflows.filter(x=>x.state==="completed");return`<section class="abos-hero"><p class="abos-kicker">Asset lifecycle</p><h1>Everything Kairos creates.</h1><p>Production assets, source packages, Shopify drafts, social content, evidence, and delivery records remain connected to the work that produced them.</p></section>${workflowCards(completed)}`;}
function growth(){return`<section class="abos-hero"><p class="abos-kicker">Growth intelligence</p><h1>Observe. Learn. Improve.</h1><p>Kairos connects performance to the next production cycle. Verified commerce and content data drive experiments; unsupported metrics are never invented.</p><div class="abos-actions"><button class="abos-primary" data-growth>Build growth plan</button><button class="abos-secondary" data-revenue>Review revenue intelligence</button></div></section><section class="abos-grid">${metric("Experiments","Queued")}${metric("Content loop","Active")}${metric("Store changes","Approval-gated")}${metric("Paid spend","Protected")}</section>`;}
function settings(){return`<section class="abos-hero"><p class="abos-kicker">Controls</p><h1>Bounded autonomy.</h1><p>Automatic reads, drafting, validation, packaging, and approved-plan execution. Live publication, pricing, spending, customer messages, and destructive operations remain explicitly protected.</p><div class="abos-actions"><button class="abos-secondary" data-open-legacy>Open advanced system controls</button></div></section>`;}
function approvalCard(item){return`<article class="abos-card"><div class="abos-card-top"><div><h3>${esc(item.title||"Approval item")}</h3><p>${esc(item.summary||"")}</p></div><span class="abos-pill">${esc(item.state||"pending")}</span></div><div class="abos-card-actions">${item.state==="pending"?`<button data-action="approve" data-item="${esc(item.id)}">Approve</button><button data-action="fix" data-item="${esc(item.id)}">Fix</button><button data-action="deny" data-item="${esc(item.id)}">Deny</button>`:""}</div></article>`;}
function workflowCards(list){return list.length?`<div class="abos-card-list">${list.map(item=>`<article class="abos-card"><div class="abos-card-top"><div><h3>${esc(item.title||item.workflowType||item.id||"Kairos work")}</h3><p>${esc(item.summary||item.objective||`${item.completedTasks||0} of ${item.taskCount||0} tasks completed`)}</p></div><span class="abos-pill">${esc(item.state||"queued")}</span></div></article>`).join("")}</div>`:`<div class="abos-empty">No work is currently listed.</div>`;}
function metric(name,value){return`<article class="abos-metric"><span>${esc(name)}</span><strong>${esc(value)}</strong></article>`;}
function bind(){root.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>{state.view=b.dataset.view;render();});root.querySelector("[data-open-brief]")?.addEventListener("click",()=>{state.view="approvals";render();});root.querySelectorAll("[data-open-legacy]").forEach(b=>b.onclick=openLegacy);root.querySelector("[data-approve-plan]")?.addEventListener("click",approvePlan);root.querySelectorAll("[data-action]").forEach(b=>b.onclick=()=>decide(b.dataset.item,b.dataset.action));root.querySelector("[data-run-objective]")?.addEventListener("click",runObjective);root.querySelector("[data-objective]")?.addEventListener("input",e=>state.objective=e.target.value);root.querySelector("[data-manuscript]")?.addEventListener("click",()=>window.dispatchEvent(new CustomEvent("kairos:manuscript-studio:open")));root.querySelector("[data-social]")?.addEventListener("click",()=>window.dispatchEvent(new CustomEvent("kairos:social-production:open")));root.querySelector("[data-growth]")?.addEventListener("click",()=>runHub("growth-plan","Build the next evidence-based growth plan for Mindset Media Group."));root.querySelector("[data-revenue]")?.addEventListener("click",()=>runHub("revenue-intelligence","Review current verified commerce performance and identify the next best action."));}
async function decide(itemID,decision){const note=decision==="fix"?(prompt("What should Kairos correct?")||""):"";state.loading=true;render();try{const{response,body}=await json("/api/executive-briefing/decide",{method:"POST",headers:headers(),body:JSON.stringify({itemID,decision,note,actor:"Executive"})});if(!response.ok)throw new Error(body?.error?.message||"Decision failed.");state.briefing=body.briefing;}catch(e){state.error=e.message;}finally{state.loading=false;render();}}
async function approvePlan(){const pending=items().filter(x=>x.state==="pending"&&!isProtected(x));for(const item of pending)await decide(item.id,"approve");await refresh();}
function isProtected(item){const text=`${item.category||""} ${item.title||""} ${item.summary||""}`.toLowerCase();return["publish","price","pricing","spend","customer","refund","delete","destructive","legal"].some(word=>text.includes(word));}
async function runObjective(){const objective=root.querySelector("[data-objective]")?.value.trim()||"";if(objective.length<3){state.error="State the business outcome before Kairos begins.";render();return;}await runHub("objective",objective);state.objective="";state.view="today";await refresh();}
async function runHub(action,objective){state.loading=true;render();try{const{response,body}=await json("/api/hub/run",{method:"POST",headers:headers(),body:JSON.stringify({action,objective})});if(!response.ok)throw new Error(body?.error?.message||"Kairos could not start the work.");}catch(e){state.error=e.message;}finally{state.loading=false;render();}}
function openLegacy(){document.body.classList.remove("abos-active");root.classList.add("abos-hidden");const close=document.createElement("button");close.className="abos-legacy-close";close.textContent="Return to Executive OS";close.onclick=()=>{close.remove();root.classList.remove("abos-hidden");document.body.classList.add("abos-active");};document.body.append(close);}
function bindGlobalEvents(){window.addEventListener("kairos:executive-os:open",()=>{state.view="today";render();});}
function items(){return state.briefing?.items||[];}
function windowTitle(){const hour=Number(new Intl.DateTimeFormat("en-US",{timeZone:"America/Los_Angeles",hour:"2-digit",hourCycle:"h23"}).format(new Date()));return hour<15?"Morning operating brief":"Evening operating review";}
function label(value){return value[0].toUpperCase()+value.slice(1);}
function headers(){return{"Content-Type":"application/json","X-MMG-Client-Build":BUILD};}
async function json(url,init={}){const response=await fetch(url,{cache:"no-store",credentials:"include",...init});const text=await response.text();let body={};try{body=text?JSON.parse(text):{};}catch{body={message:text};}return{response,body};}
function esc(value){return String(value??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[c]);}
