api_version = "2026-07"

[[extensions]]
type = "ui_extension"
name = "My Downloads"
handle = "mmg-my-downloads"
uid = "c2a4f88e-ecb7-4d3e-94c8-21fa813d9e11"

[[extensions.targeting]]
target = "customer-account.page.render"
module = "./src/MyDownloads.tsx"
