/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js during local development and is committed here
// so the scaffold type-checks consistently from a fresh checkout.
