client_id = "0e2218fa78074829c6d9df9ab2fdfe95"
name = "Mindset Media Group"
handle = "mmg-customer-account-1"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = false

[build]
automatically_update_urls_on_dev = false
include_config_on_deploy = true

[access_scopes]
scopes = "customer_read_customers,customer_read_orders"
