client_id = "c59b40991414fb575c15acd4dae8cd74"
name = "Customer Account Integration"
handle = "customer-account-integration"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = false

[build]
automatically_update_urls_on_dev = false
include_config_on_deploy = true

[access_scopes]
scopes = "customer_read_customers,customer_read_orders"
